[project]
name = "comment-filter-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "reflex==0.7.14",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.11.12",
]
